export const oldCharacterScoringMetadata: Record<string, Record<string, number>> = {
  1001: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 1,
    'DEF%': 1,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1002: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 1,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1003: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0.5,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1004: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 1,
  },
  1005: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0.5,
    'CRIT DMG': 0.5,
    'Effect Hit Rate': 0.5,
    'Effect RES': 0,
    'Break Effect': 0.75,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 1,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1006: {
    'ATK': 0.5,
    'ATK%': 0.5,
    'DEF': 0.25,
    'DEF%': 0.25,
    'HP': 0.25,
    'HP%': 0.25,
    'SPD': 1,
    'CRIT Rate': 0.75,
    'CRIT DMG': 0.75,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 0.75,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 1,
    'Imaginary DMG Boost': 0,
  },
  1008: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 1,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1009: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0.5,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1013: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 1,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1101: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 1,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1102: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 1,
    'Imaginary DMG Boost': 0,
  },
  1103: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 1,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1104: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 1,
    'DEF%': 1,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0.75,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1105: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 1,
    'HP%': 1,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 1,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1106: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 1,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1107: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1108: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 1,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 1,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1109: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1110: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 1,
    'HP%': 1,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 1,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1111: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 0.75,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1112: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1201: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 1,
    'Imaginary DMG Boost': 0,
  },
  1202: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1203: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 1,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1204: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 1,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1205: {
    'ATK': 0.25,
    'ATK%': 0.25,
    'DEF': 0,
    'DEF%': 0,
    'HP': 1,
    'HP%': 1,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 1,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1206: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0.5,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1207: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 1,
  },
  1208: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 1,
    'HP%': 1,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1209: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 1,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1210: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 0.75,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1211: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 1,
    'HP%': 1,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 1,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1212: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 1,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1213: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 1,
  },
  1214: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 1,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 1,
    'Imaginary DMG Boost': 0,
  },
  1215: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1217: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 1,
    'HP%': 1,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 1,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1218: {
    'ATK': 0.5,
    'ATK%': 0.5,
    'DEF': 0.5,
    'DEF%': 0.5,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1220: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 1,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1221: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1222: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0.5,
    'DEF%': 0.5,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 1,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 1,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1223: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 1,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1224: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 1,
  },
  1301: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 1,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 1,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1302: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1303: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 1,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1304: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 1,
    'DEF%': 1,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 1,
  },
  1305: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 1,
  },
  1306: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1307: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 1,
    'Effect RES': 0,
    'Break Effect': 0.5,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 1,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1308: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 1,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1309: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1310: {
    'ATK': 1,
    'ATK%': 1,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 1,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1312: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 1,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  1314: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 1,
    'Imaginary DMG Boost': 0,
  },
  1315: {
    'ATK': 0.5,
    'ATK%': 0.5,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 0.75,
    'CRIT DMG': 0.75,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 1,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  8001: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0.5,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  8002: {
    'ATK': 0.75,
    'ATK%': 0.75,
    'DEF': 0,
    'DEF%': 0,
    'HP': 0,
    'HP%': 0,
    'SPD': 1,
    'CRIT Rate': 1,
    'CRIT DMG': 1,
    'Effect Hit Rate': 0,
    'Effect RES': 0,
    'Break Effect': 0.5,
    'Energy Regeneration Rate': 0,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 1,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  8003: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 1,
    'DEF%': 1,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0.75,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  8004: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 1,
    'DEF%': 1,
    'HP': 0.5,
    'HP%': 0.5,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0.75,
    'Effect RES': 0.75,
    'Break Effect': 0,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  8005: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 1,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
  8006: {
    'ATK': 0,
    'ATK%': 0,
    'DEF': 0.75,
    'DEF%': 0.75,
    'HP': 0.75,
    'HP%': 0.75,
    'SPD': 1,
    'CRIT Rate': 0,
    'CRIT DMG': 0,
    'Effect Hit Rate': 0,
    'Effect RES': 0.75,
    'Break Effect': 1,
    'Energy Regeneration Rate': 1,
    'Outgoing Healing Boost': 0,
    'Physical DMG Boost': 0,
    'Fire DMG Boost': 0,
    'Ice DMG Boost': 0,
    'Lightning DMG Boost': 0,
    'Wind DMG Boost': 0,
    'Quantum DMG Boost': 0,
    'Imaginary DMG Boost': 0,
  },
}
