struct ComputedStats {
  HP_P: f32,
  ATK_P: f32,
  DEF_P: f32,
  SPD_P: f32,
  HP: f32,
  ATK: f32,
  DEF: f32,
  SPD: f32,
  CR: f32,
  CD: f32,
  EHR: f32,
  RES: f32,
  BE: f32,
  ERR: f32,
  OHB: f32,

  DMG_BOOST: f32,

  // Base
  BASE_HP: f32,
  BASE_ATK: f32,
  BASE_DEF: f32,
  BASE_SPD: f32,

  // Secondary conversions
  UNCONVERTIBLE_HP_BUFF: f32,
  UNCONVERTIBLE_ATK_BUFF: f32,
  UNCONVERTIBLE_DEF_BUFF: f32,
  UNCONVERTIBLE_SPD_BUFF: f32,
  UNCONVERTIBLE_CR_BUFF: f32,
  UNCONVERTIBLE_CD_BUFF: f32,
  UNCONVERTIBLE_EHR_BUFF: f32,
  UNCONVERTIBLE_BE_BUFF: f32,
  UNCONVERTIBLE_OHB_BUFF: f32,
  UNCONVERTIBLE_RES_BUFF: f32,
  UNCONVERTIBLE_ERR_BUFF: f32,

  // EHP
  DMG_RED: f32,
  EHP: f32,

  // Misc configs
  SUMMONS: f32,
  MEMOSPRITE: f32,
  ENEMY_WEAKNESS_BROKEN: f32,
  MEMO_BUFF_PRIORITY: f32,
  DEPRIORITIZE_BUFFS: f32,
  COMBO_DMG: f32,

  // DOT
  DOT_CHANCE: f32,
  EFFECT_RES_PEN: f32,
  DOT_SPLIT: f32,
  DOT_STACKS: f32,

  // Heal / Shield
  HEAL_TYPE: f32,
  HEAL_FLAT: f32,
  HEAL_SCALING: f32,
  HEAL_VALUE: f32,
  SHIELD_FLAT: f32,
  SHIELD_SCALING: f32,
  SHIELD_VALUE: f32,
  SHIELD_BOOST: f32,

  ATK_SCALING: f32,
  DEF_SCALING: f32,
  HP_SCALING: f32,
  SPECIAL_SCALING: f32,

  ATK_P_BOOST: f32,
  CR_BOOST: f32,
  CD_BOOST: f32,

  VULNERABILITY: f32,
  RES_PEN: f32,
  DEF_PEN: f32,

  TOUGHNESS_DMG: f32,
  SUPER_BREAK_MODIFIER: f32,
  BREAK_EFFICIENCY_BOOST: f32,

  FINAL_DMG_BOOST: f32,
}