// ── Existing types (extended) ────────────────────────────────────────────────

// Grouped by engine behaviour, not by attribute granularity.
// Each group is handled by a distinct code path in the simulation engine.
export type InterventionType =
  | 'av_advance'    // Direct AV position shift
  | 'av_delay'
  | 'spd_up'        // Speed change — triggers gauge conservation math
  | 'spd_down'
  | 'energy_gain'   // Personal energy value change (Phase 2+)
  | 'energy_loss'
  | 'sp_gain'       // Team Skill Point change — instant (Phase 2+)
  | 'sp_loss'
  | 'sp_cap_up'     // Temporary SP ceiling change, has duration (Phase 2+)
  | 'sp_cap_down'
  | 'stat_buff'     // Attribute modifier — stat field specifies which (Phase 3+)
  | 'stat_debuff'

export type InterventionUnit = 'flat' | 'percent'

export type Intervention = {
  id: string
  triggerAv: number
  // During action (before): fires right before the target character's beforeActionIndex-th action;
  // the spd buff is consumed by that very action (no effect when durationTurns=1)
  // When both beforeCharId and afterCharId are undefined = global "during action": not bound to any
  // character, fires once based purely on triggerAv (kept for backward compat / flat-view scenarios)
  beforeCharId?: string
  // Which action (0-based) this fires before; only meaningful when beforeCharId is set;
  // undefined is equivalent to 0 (before the 1st action)
  beforeActionIndex?: number
  // End-of-action instant (after): fires right after the target character's afterActionIndex-th action ends
  afterCharId?: string
  // Which action (0-based) this fires after; only meaningful when afterCharId is set;
  // undefined is equivalent to 0 (after the 1st action)
  afterActionIndex?: number
  // @deprecated Superseded by beforeCharId; kept only for backward compat with old data. The engine no longer reads this field.
  sourceCharId?: string
  type: InterventionType
  targets: string[]
  value: number
  unit: InterventionUnit
  durationTurns: number
  // Extended fields (all optional to preserve backward compat with persisted data)
  stat?: string                         // stat_buff/debuff: which attribute to affect
  buffKind?: 'direct' | 'aura'         // Tick basis; default 'direct' if omitted
  auraTargets?: 'all_allies' | 'all_enemies'
}

// Shared contract between ActionDisplayPanel (emits requests) and EditPanel (consumes them), lifted in
// AvVisualizerTab. 'add' carries the timing context (before/after/global) the request originated from;
// 'edit' carries the full intervention being edited.
export type EditRequest =
  | { mode: 'add'; beforeCharId?: string; beforeActionIndex?: number; afterCharId?: string; afterActionIndex?: number }
  | { mode: 'edit'; intervention: Intervention }

// Drives which component renders in the right-side context panel of AvVisualizerTab.
// Replaces the single EditRequest state — each kind maps to a different panel component.
export type RightPanelContext =
  | { kind: 'idle' }
  | { kind: 'add-branch'; triggerAv: number; afterCharId?: string; afterActionIndex?: number; beforeCharId?: string; beforeActionIndex?: number; afterUltId?: string; insertBeforeUltId?: string; ultTimingReference?: UltTiming }
  | { kind: 'intervention'; request: EditRequest }
  | { kind: 'action-config'; characterId: string; actionIndex: number }
  | { kind: 'character-state'; characterId: string; actionIndex?: number; turnKind?: TurnKind; stateSnapshot?: CharacterBattleState }
  | { kind: 'ult-caster'; timing: UltTiming; insertAfterId?: string; insertBeforeUltId?: string }
  | { kind: 'ult-effects'; casterId: string; targets?: string[] }

// ── New types ─────────────────────────────────────────────────────────────────

// Turn kind determines whether a BattleEvent participates in AV queue calculations.
// 'normal' events are AV-driven and affected by speed/advance/delay.
// 'ult' and 'extra' events are inserted at fixed points and are immune to AV manipulation.
export type TurnKind = 'normal' | 'ult' | 'extra'

// Actions a user can select at a normal action node.
// 'ult' is intentionally excluded — ultimates are inserted as independent UltInsertion events.
// 'follow_up' is generated by the engine, not selected by the user.
export type ActionChoice = 'basic' | 'skill' | 'follow_up'

// Semantic target descriptor used in InterventionTemplate.
// Distinct from Intervention.targets (which holds resolved characterId[]).
export type TargetType =
  | 'self'
  | 'single_ally'    // User picks a target; UI shows a dropdown
  | 'all_allies'
  | 'single_enemy'
  | 'blast'          // 3 fixed enemies
  | 'all_enemies'    // 5 fixed enemies
  | 'team'           // The shared team SP pool — not a per-character target

// Skill effect template bound to a CharacterBattleConfig ability.
// Does not contain triggerAv or resolved target IDs — the engine fills those in at action time.
// Uses a discriminated union so required fields differ by type group:
//   - Instant effects:   no duration, no buffKind
//   - SP instant:        targets locked to 'team'; unit always 'flat'
//   - SP cap effects:    duration required; targets locked to 'team'; unit always 'flat'
//   - Speed effects:     duration required, buffKind optional (can be aura e.g. Robin ult)
//   - Stat effects:      duration + stat required, buffKind optional
export type InterventionTemplate =
  | {
      type: 'av_advance' | 'av_delay' | 'energy_gain' | 'energy_loss'
      targets: TargetType
      value: number
      unit: 'flat' | 'percent'
    }
  | {
      type: 'sp_gain' | 'sp_loss'
      targets: 'team'           // SP is always a team-level resource
      value: number
      unit: 'flat'              // SP counts are always integers
    }
  | {
      type: 'sp_cap_up' | 'sp_cap_down'
      targets: 'team'
      value: number
      unit: 'flat'
      durationTurns: number     // e.g. Sparkle ult: +2 cap for 2 turns
    }
  | {
      type: 'spd_up' | 'spd_down'
      targets: TargetType
      value: number
      unit: 'flat' | 'percent'
      durationTurns: number
      buffKind?: 'direct' | 'aura'
      auraTargets?: 'all_allies' | 'all_enemies'
    }
  | {
      type: 'stat_buff' | 'stat_debuff'
      targets: TargetType
      stat: string               // Required: e.g. 'CR' | 'CD' | 'BREAK_EFFICIENCY'
      value: number
      unit: 'flat' | 'percent'
      durationTurns: number
      buffKind?: 'direct' | 'aura'
      auraTargets?: 'all_allies' | 'all_enemies'
    }

// Per-character battle behaviour definition. Hand-written in battleConfigs/<Name>.ts.
// max_sp is read from game_data.json at runtime, not stored here.
// Initial energy (max_sp × 50%) is applied by the engine, not configured here.
export type CharacterBattleConfig = {
  characterId: string
  energyType: 'standard' | 'special'   // 'special' not supported in Phase 1 (e.g. Huangque)
  // Permanent SP cap bonus applied at battle start, as long as this character is in the team.
  // Engine sums spCapBonus across all configs when initialising TeamBattleState.spMax.
  // e.g. Sparkle: +3 (raises team cap from 5 to 8 permanently)
  spCapBonus?: number
  ultThreshold?: number   // 触发大招所需的最低能量，默认等于 max_sp
  ultEnergyCost?: number  // 每次释放扣除的能量，默认等于 ultThreshold；低于 max_sp 时支持部分保留能量
  abilities: {
    basic:      InterventionTemplate[]
    skill:      InterventionTemplate[]
    ult:        InterventionTemplate[]  // Triggered by UltInsertion, not an ActionChoice
    follow_up?: InterventionTemplate[]
  }
  summon?: {
    id: string
    baseSpd: number
    ownerId: string
    derivedSpd?: (ownerExtras: Record<string, number>) => number
  }
  extrasOnAction?: Array<{
    ability: ActionChoice | 'ult'
    patch: (currentExtras: Record<string, number>) => Record<string, number>
  }>
}

// User's decision at a normal action node in the Timeline.
// Resurgence fields (Seele) are attached to the triggering normal-turn Override
// rather than being a separate structure, so no extra ID scheme is needed.
export type ActionNodeOverride = {
  characterId: string
  actionIndex: number             // 0-based index among this character's normal turns
  choice: ActionChoice
  targets?: string[]              // Resolved target characterIds for single_ally effects
  triggerResurgence?: boolean     // Seele: insert a TurnKind 'extra' turn after this action
  resurgenceChoice?: ActionChoice // Action for the extra turn (defaults to 'basic')
  resurgenceTargets?: string[]    // Targets for the extra turn if single_ally
}

// Where in the timeline to insert an ultimate.
// Mirrors the existing before/after intervention timing model.
export type UltTiming =
  | { type: 'during_action'; charId: string; actionIndex: number }
  | { type: 'after_action';  charId: string; actionIndex: number }
  | { type: 'at_av';         av: number }

// An ultimate insertion request stored in the session.
// The engine validates caster energy >= ultThreshold (or max_sp if omitted) before producing a BattleEvent.
export type UltInsertion = {
  id: string
  casterId: string
  timing: UltTiming
  targets?: string[]
}

// A currently active effect that is ticking down, stored in CharacterBattleState.
// buffKind is required (not optional) because runtime state must have a determined tick basis.
export type ActiveIntervention = {
  id: string
  sourceCharacterId: string
  sourceAbility: ActionChoice | 'ult' | 'external'  // 'external' = manually added Intervention
  type: InterventionType
  stat?: string
  value: number
  unit: 'flat' | 'percent'
  remainingTurns: number
  buffKind: 'direct' | 'aura'    // direct: tick on receiver's turn; aura: tick on caster's turn
  auraTargets?: 'all_allies' | 'all_enemies'
  auraEffect?: {
    type: InterventionType
    stat?: string
    value: number
    unit: 'flat' | 'percent'
  }
}

// Complete state snapshot of a single entity (character or summon) at a point in time.
// Stored in BattleEvent.stateBefore / stateAfter for checkpoint-based re-simulation.
export type CharacterBattleState = {
  energy: number
  spd: number                              // Current effective speed (including SPD buffs)
  activeInterventions: ActiveIntervention[]
  extras: Record<string, number>           // Character-specific state; 0 = inactive
}

// Snapshot of the team-shared Skill Point pool at a point in time.
// spMax defaults to 5; temporarily raised by effects like Sparkle ult (sp_cap_up).
export type TeamBattleState = {
  sp: number
  spMax: number
}

// Unified entity type for the simulation queue and Timeline rows.
// Replaces TimelineCharacter (which was defined locally in Timeline.tsx).
export type BattleEntity = {
  id: string
  type: 'character' | 'summon'
  ownerId?: string    // summon only: points to the owning character's id
  name: string
  baseSpd: number     // Speed without buffs; needed for percent-based SPD buff math
  spd: number         // Current effective speed
  color: string
  slotIndex: number
}

// Primary output type of the simulation engine.
// Replaces SimEvent. stateBefore/stateAfter and team fields are placeholder empty objects
// until the engine is extended in Step 3 (simulateBattle.ts).
export type BattleEvent = {
  av: number
  characterId: string
  actionIndex: number
  effectiveSpd: number
  turnKind: TurnKind
  actionChoice: ActionChoice | 'ult'
  stateBefore: Record<string, CharacterBattleState>
  stateAfter: Record<string, CharacterBattleState>
  teamStateBefore: TeamBattleState
  teamStateAfter: TeamBattleState
  ultInsertionId?: string   // set for turnKind='ult' events; links back to the UltInsertion that produced this event
  damageResult?: number
  damageStale?: boolean
}
