import { Flex, List, theme, Typography } from 'antd'
import { officialOnly } from 'lib/constants/constants'
import { Assets } from 'lib/rendering/assets'
import { AppPages } from 'lib/state/db'
import { ColorizedLinkWithIcon } from 'lib/ui/ColorizedLink'
import React, { ReactElement, useMemo } from 'react'

const { useToken } = theme
const { Text } = Typography

type ChangelogContent = { title: string; date: string; content: string[] }

export default function ChangelogTab(): React.JSX.Element {
  const { token } = useToken()

  const activeKey = window.store((s) => s.activeKey)
  const changelogContent = useMemo(() => getChangelogContent(), [])

  if (activeKey != AppPages.CHANGELOG) {
    // Don't load images unless we're on the changelog tab
    return (<></>)
  }

  function listToDisplay(content: string[], contentUpdate: ChangelogContent) {
    const display: ReactElement[] = []
    let i = 0
    for (const entry of content) {
      if (entry.endsWith('.webp')) {
        display.push(
          <img
            key={i++}
            src={Assets.getChangelog(`${contentUpdate.date}/${entry}`)}
            loading='lazy'
            style={{
              border: `2px solid ${token.colorBgContainer}`,
              margin: 5,
              maxWidth: 1200,
            }}
          />,
        )
      } else if (entry.startsWith('https')) {
        display.push(
          <li key={i++}>
            <ColorizedLinkWithIcon
              text={entry}
              url={entry}
              key={i++}
            />
          </li>,
        )
      } else {
        display.push(
          <li key={i++}>
            <Text style={{ fontSize: 16 }}>{entry}</Text>
          </li>,
        )
      }
    }

    return (
      <Flex vertical>
        <Typography.Title style={{ marginLeft: 20 }}>
          <u>
            {`Update ${contentUpdate.date}`}
          </u>
        </Typography.Title>
        <ul>
          {display}
        </ul>
      </Flex>
    )
  }

  return (
    <List
      itemLayout='vertical'
      size='large'
      pagination={{
        onChange: (page) => {
          console.log(page)
        },
        position: 'bottom',
        align: 'start',
        pageSize: 4,
      }}
      dataSource={changelogContent}
      renderItem={(item) => (
        <List.Item
          key={item.title}
        >
          {listToDisplay(item.content, item)}
        </List.Item>
      )}
    />
  )
}

function leaks(str: string) {
  return officialOnly ? '' : str
}

/*
 NOTES:
 */

function getChangelogContent() {
  const changelog: ChangelogContent[] = [
    {
      title: '',
      date: '2025-02-25',
      content: [
        leaks(`Updated content to v3.2v1`),
        leaks(`Added Castorice showcase`),
        leaks(`castorice.webp`),
        leaks(`Added Anaxa showcase`),
        leaks(`anaxa.webp`),
        `Fix: Improved GPU optimization performance and faster compile times`,
        `Fix: Combo DMG optimization on GPU on Mac no longer crashes`,
      ],
    },
    {
      title: '',
      date: '2025-02-21',
      content: [
        `Added an Optimization Results Analysis panel with in depth information & comparisons for optimizer results`,
        `analysis.webp`,
        `Enabled i18n support for Korean`,
        `Enabled i18n support for Vietnamese`,
        `vnkr.webp`,
        `Added a display for tracking sources of combat buffs on the showcase analysis and optimizer analysis`,
        `buffs.webp`,
        `Improved the additional warp resources selector to include warp income per half patch`,
        `income.webp`,
        `Added an overwrite button to the custom stats simulation tool, to edit and replace an existing simulation`,
        `replace.webp`,
        `UID is now shown by default on the character showcase`,
        `uid.webp`,
        `Added a UID show / hide selector on the showcase customization toolbar`,
        `showUid.webp`,
        `Added an importer option to only import characters that are already in the optimizer`,
        `import.webp`,
        `Bronya / Remembrance Trailblazer / Sunday Crit DMG limits are increased to 400% on optimizer conditionals`,
        `cd.webp`,
        `The optimizer now selects the character's currently equipped relics for stat display and the analysis panel`,
        `Character scores are now set to "?" ranking for non-6 piece builds and missing light cones`,
        `Improved UI performance for loading showcases`,
        `Optimization performance improvements for CPU engine`,
        `Fix: Forcing weakness break from certain character conditionals now also correctly applies the global weakness broken DMG multiplier`,
        `Fix: Optimizer input changes now save correctly after page refresh`,
        `Fix: Aglaea and Remembrance Trailblazer conditionals now enable The Wondrous BananAmusement Park set by default`,
        `Fix: Memosprites now correctly receive SPD buffs`,
        `Fix: Memosprites now correctly calculate Super Break DMG`,
        `Fix: Additional DMG instances now correctly get calculated without ability-type DMG boosts`,
        `Fix: Tribbie E1 now correctly applies to the entire team`,
        `Fix: True DMG now correctly applies to DOT and Break DMG instances`,
        `Fix: Home page UID input now searches on Enter key press`,
        `Fix: Damage upgrades will no longer recommend an existing main stat`,
        `Fix: Damage upgrades will no longer recommend other ropes when the benchmark is matching Energy Regen rope`,
        `Fix: Mydei now correctly uses basic HP for conversion instead of combat HP`,
        `Fix: Sacerdos' Relived Ordeal set now syncs correctly on optimizer teammates`,
        `Fix: Bone Collection's Serene Demesne and Giant Tree of Rapt Brooding sets are now applied correctly in SubDPS scoring mode`,
        `Balance: Argenti's benchmarks now equalize for Energy Regen rope`,
        `Balance: Tribbie's SPD weight updated 0 -> 1.0 again after buffs`,
        `Balance: Tribbie's benchmarks now use Genius of Brilliant Stars by default, while matching the user's Poet of Mourning Collapse set`,
        `Balance: Tribbie's combo rotation now uses 4 -> 3 FUAs`,
        `Balance: Blade's default benchmark set is now Bone Collection's Serene Demesne`,
      ],
    },
    {
      title: '',
      date: '2025-01-26',
      content: [
        `Updated content to version 3.1v3`,
        `Added a Warp Planner tab for calculating warp probabilities`,
        `warp.webp`,
        `Added a new customization sidebar for showcase scoring and stat views`,
        `stats.webp`,
        `Stat trace trees can now be customized, allowing SPD traces to be disabled for Poet of Mourning Collapse sets for example`,
        `trace.webp`,
        'The SPD precision selector will allow for toggling between 1 and 3 decimal places for SPD displays for precise SPD tuning',
        `Modified traces will show with an asterisk *`,
        `spd.webp`,
        'The SPD weight selector will allow for toggling the value of SPD substats between 0% and 100% for better grading of low SPD builds',
        `0% weight SPD scores are marked with a special boots icon when SPD = 0 is the only customized weight`,
        `weight.webp`,
        `The SPD benchmark selector will force the benchmark simulations to target a specific SPD value that is lower than your character's SPD`,
        `benchmark.webp`,
        `Scores with a modified SPD benchmark will show their SPD target on the DPS score display`,
        `benchmarkScore.webp`,
        `The Buff Priority selector will allow for toggling between making the character the primary target of single target buffs or not`,
        `priority.webp`,
        `When a character is on Buff Priority: Low, they will no longer be targeted with single target buffs, and will be labeled as a Sub DPS`,
        `Their Combat Stats and DPS score will also adjust based on their buff status`,
        `subdps.webp`,
        `Updated the auto color selection algorithm for custom portraits`,
        `Removed the CV value display from character cards, adjusted the logic for showing relevant stats`,
        `Fixed: Showcase shadows on mobile screenshot downloads`,
        `Fixed: Various formatting issues were corrected in conditional text popups`,
        `Fixed: Relic potential scoring now matches the main stats for optimal main stat relics`,
        `Balance: Added ERR rope to Tribbie scoring`,
        `Balance: Set Tribbie's default SPD weight to 0`,
        `Balance: Set Tribbie's default set to Poet of Mourning Collapse`,
        `Balance: Enabling Sub DPS mode by default for Tribbie / Aventurine / Fugue / Serval / Topaz / Moze / March 7th (Hunt)`,
      ],
    },
    {
      title: '',
      date: '2025-01-13',
      content: [
        `Updated content to version 3.1v1`,
        'Added Tribbie showcase',
        'tribbie.webp',
        'Added Mydei showcase',
        'mydei.webp',
        'Added new relic sets for 3.1',
        `sets.webp`,
        'Added new relic rating columns for relic reroll potential',
        '— The reroll column shows the average potential of the relic after using reroll dice on it',
        '— The reroll delta column shows the expected increase in potential from the current relic to its post-reroll stats',
        'ratingColumns.webp',
        'The reroll and delta columns are now sortable in the relics grid',
        'columns.webp',
        'Added buff priority selectors for Remembrance characters, for choosing between prioritizing the summoner or memosprite when receiving single target buffs',
        'buffPrio.webp',
        'Fix: Added Aglaea missing Seam Stitch conditional',
        'Fix: Added Black Swan missing E4 conditional',
        'Fix: Dmg RES and Eff RES enemy options labels were swapped',
        'Fix: Showcase rendering on mobile devices',
        'Fix: Relic potential changed between re-scores in certain cases',
        'Balance: Added ERR rope to Serval scoring',
        'Balance: Added ERR rope to Welt scoring',
      ],
    },
    {
      title: '',
      date: '2025-01-07',
      content: [
        `Added a no-scoring showcase card view`,
        `noScore.webp`,
        `Added dark mode for showcase card colors`,
        `Adjusted showcase card colors for various characters`,
        `dark.webp`,
        `Content has been updated for version 3.0`,
        `Added Memosprite handling logic for remembrance characters`,
        `Optimizer sidebar now has a Summoner / Memosprite stats view selector which changes the optimizer stat targets, similar to Combat / Basic mode`,
        `memoView.webp`,
        `On the optimizer grid, columns for Memosprite stats are now denoted in superscript such as Σ ATKᴹ`,
        `Added a new ability damage column for Memosprite skills: SKILLᴹ DMG`,
        `memoSkill.webp`,
        `The Combo DMG ability rotation panel is updated to include SKILLᴹ DMG`,
        `memoCombo.webp`,
        `Aglaea DPS scoring is now active, defaulting to Hero of Triumphant Song + The Wondrous BananAmusement Park sets`,
        `aglaea.webp`,
        `Remembrance Trailblazer True DMG scoring conditionals are now active`,
        `rmc.webp`,
        `Single target buffs are assumed to apply to the summoner, certain Sunday buffs / RMC buffs / team buffs can apply to both summoner and memo`,
        `Hero of Triumphant Song and Poet of Mourning Collapse sets are now active`,
        `heroPoet.webp`,
        `Added rerun characters to showcase presets`,
        `rerun.webp`,
        `Added support for Japanese translations in the i18n menu`,
        `jp.webp`,
        `Imported characters' light cones are now preselected on character / teammate menus`,
        `Updated menu banner to identify no leaks / beta sites`,
        `Fix: Showcase Damage Improvements tab now shows Elemental + Ability DMG as "DMG %" to not overflow space`,
        `Fix: The 100% benchmark for DPS scoring will now exactly match the user's SPD stat (except for Poet of Mourning Collapse sets)`,
        `Fix: The 200% incorrectly assumed the 100%'s boots were optimal - now, 200% will always choose the optimal SPD / ATK boots, resulting in possible score decreases`,
        `Balance: Added diminishing returns for 100% benchmark with high SPD, for characters like Kafka`,
        `Balance: Benchmarks with the Poet of Mourning Collapse set will now match the set's SPD threshold at 110 or 95 SPD, instead of matching the user's SPD`,
        `Balance: The Wondrous BananAmusement Park set is now matched for summoner benchmarks`,
        `Balance: Updated some outdated characters' relic / ornament benchmark sets for combat score`,
        `Balance: 4 star relics are now rated as "?"`,
        `Balance: Scoring changes for version 3.0 dice and resin`,
        `— Previously, main stats were given between 1 to 2 free substats worth of score to balance for rarity / difficulty of obtaining optimal the main stat`,
        `— This was balanced for version 1.x but now with the addition of reroll dice and substat resin in 3.x, optimal main stats are much easier to obtain`,
        `— We're adjusting this free score to be worth 1 substat roll for all main stats, which will result in a slight Character / Relic score decrease`,
        `— For Combat scoring, the scaling thresholds have also been updated for grades above the 100% benchmark to adjust for score inflation from dice / resin`,
        `score.webp`,
      ],
    },
    {
      title: '',
      date: '2024-11-27',
      content: [
        `The optimizer site has a new home page`,
        `home.webp`,
        `Updated the character showcase design`,
        `showcase.webp`,
        `Added a new showcase theme customization sidebar`,
        `custom.webp`,
        `I18n support has been enabled with support for: Français, Português (BR), 中文`,
        `i18n.webp`,
        `Added healing and shielding columns and filters for sustain characters, and adjusted their default sort columns`,
        `heal.webp`,
        `Added new selector conditional type for healing and shielding sources`,
        `healSource.webp`,
        `Added a new AEON tier for DPS score at 150% with verified-only relics`,
        `aeon.webp`,
        `Incorrect main stat pieces will now get a (?) rating on the character showcase`,
        `question.webp`,
        `The optimizer grid will now remove irrelevant columns for characters to hide the full-zero columns`,
        `Made slight adjustments to relic scoring - flat stats are now valued at a static 0.40x of their percentage counterpart`,
        `Fix: Fugue E4 break DMG buff now calculates correctly`,
        `Balance: Sim scoring will now match Energy Regeneration rope for certain character / eidolon combinations`,
        `Balance: Fugue now has additional Break instances in her combo damage rotation to push towards break focus`,
      ],
    },
    {
      title: '',
      date: '2024-10-19',
      content: [
        `Updated content for version 2.7`,
        `fugue.webp`,
        `Added a new ability rotation calculation methodology, where damage abilities are evaluated sequentially for buff activation`,
        `rotation.webp`,
        `Added an Advanced Rotation panel for full customizability of buff uptime and in-battle conditional calculations for the entire team`,
        `Simple mode will automatically apply presets, while Advanced mode grants full control. Improved preset accuracy is under development`,
        `advanced.webp`,
        `DPS score now shows the combo rotation abilities`,
        `abilities.webp`,
        `Added i18n support, looking for contributors to help translate the website`,
        `i18n.webp`,
        `Removed Stat Weight sort and filter options for optimizer simplification. The stat weight column still remains`,
        `Sacerdos has been added as a personal relic set conditional for characters with self buffs`,
        `Fix: The Recommended Presets button no longer resets weighted rolls per relic`,
        `Fix: Improved Firefox optimizer search performance`,
        `Balance: DPS score overvalued ATK boots in certain situations with large amount of speed buffs, mostly affects ATK boots Kafka S1 builds`,
        `Balance: Jiaoqiu is now recommended ATK / ERR rope by default`,
        `Balance: Ruan Mei can now use all mains stats for feet`,
        `Balance: Shadowed by Night light cone now has SPD buff enabled by default`,
      ],
    },
    {
      title: '',
      date: '2024-09-20',
      content: [
        `Added a Relic Locator tool to the Relics tab for finding the relic's row / column in the inventory`,
        `locator.webp`,
        `Updated all assets files to high quality images for character portraits, light cones, icons`,
        `Readjusted the crop and zoom for the new portrait assets`,
        `Reduced the light cone portrait height for Combat scoring view`,
        `Moved the Character Menu button to the top of the Characters tab for better findability`,
        `characterTab.webp`,
        `Reliquary is now updated for 2.5`,
        `reliquary.webp`,
        `Updated Rappa's default scoring team`,
        `rappaTeam.webp`,
        `Added pointer cursors to clickable icons`,
        `Optimizer tab character and teammate menus are now open upon clicking their icons`,
        `Fix: Save file now correctly loads previous scoring algorithm changes`,
        `Fix: Pioneer Diver of Dead Waters 0x conditional now correctly applies`,
        `Balance: Lowered the scoring penalty for missing flat stat breakpoints for combat scoring`,
        `Balance: Updated Pioneer Diver of Dead Waters default conditional to 3x+ for characters with debuffs`,
        `Balance: Changed Rappa's scoring weights from 1 ATK / 1 SPD / 1 BE to 0.5 ATK / 1 SPD / 1 BE`,
      ],
    },
    {
      title: '',
      date: '2024-09-08',
      content: [
        `Added GPU acceleration to perform calculations on the graphics card for a significant improvement in optimizer search speed`,
        `Enabling GPU acceleration will improve the optimizer's search speed to hundreds of millions of permutations per second, up to billions on high end devices`,
        `3 compute engine options are now available`,
        `— GPU Experimental: Fastest search speed but potentially unsupported on some devices`,
        `— GPU Stable: Fast search speed for general device compatability (default)`,
        `— CPU Only`,
        `GPU acceleration only supported on Windows & Mac: Chrome, Opera, Edge browsers, Linux: Chromium browsers with a cli flag`,
        `gpu.webp`,
        `Updated the substat scoring algorithm to score relics stats relative to the maximum possible score on the relic`,
        `This means that when a weighted substat is occupied by the main stat, the score value of the remaining substat weights increases`,
        `Default character weights were rebalanced to account for this, and now more accurately reflect the true value of substats, for example:`,
        `Firefly's previous weight of 1.0 ATK / 1.0 SPD / 1.0 BE has been updated to 0.5 ATK / 1.0 SPD / 1.0 BE since her passive converts ATK at roughly half the value of BE`,
        `While the ATK weight was reduced, this actually makes the score value of SPD and BE higher since the new system scores stats relative to the other weights`,
        `The updated substat weight methodology can be viewed from the Scoring Algorithm menu`,
        `scoring.webp`,
        `Updated the copy screenshot button to work for all browsers. Also works on mobile devices now`,
        `screenshot.webp`,
        `Updated the Edit Portrait workflow to be smoother. Added an 'Upload new image' button to change the portrait`,
        `portrait.webp`,
        `Multiple relics can now be selected and deleted simultaneously on the Relics tab with Shift + Click and Ctrl + Click`,
        `multiselect.webp`,
        `Added a new setting for enabling / disabling a full inventory rescore on page load. Disable for faster load times on large inventories`,
        `scoreSetting.webp`,
        `Results limits for the optimization target have been changed to be compatible with GPU optimizer - now defaults to 1024 results`,
        `resultCount.webp`,
        `The Relic Insights tool now opens the character scoring panel on click, and now updates correctly when the selected character is changed`,
        `insights.webp`,
        `Updated with version 2.6v1 content`,
        `rappa.webp`,
        `Clicking the light cone portrait on character cards now bring up the Edit Character / Light Cone menu`,
        `Added a confirmation popup for resetting optimizer filters`,
        `Added on-hit buffs for the character's primary ability to the Combat stats section of scoring cards`,
        `Relic scorer URL can now be shared with user IDs included`,
        `Relic cards now show a border on hover`,
        `Performance: Improved relic scorer stability`,
        `Performance: Improved portrait image loading times, fixed images jumping around when loading`,
        `Performance: Improved character card loading time for Combat score cards`,
        `Performance: Improved relic import responsiveness`,
        `Performance: Improved editing and saving relics responsiveness`,
        `Fix: Some custom portrait dimensions were not cropping correctly`,
        `Fix: On the Relics tab, relics will remain selected after editing it`,
        `Fix: Prevent Combat stats panel from overflowing on scoring cards`,
        `Fix: Firesmith of Lava-Forging 4p was incorrectly adding combat buffs`,
        `Fix: Relic / ornament set selector on Optimizer tab was incorrectly rendering overflowing tags`,
        `Fix: But the Battle Isn't Over was not showing the Energy Regeneration Rate passive`,
        `Balance: Allow ATK % rope on Lingsha default scoring`,
        `Balance: Fixed a bug where the 200% benchmark used an extra substat roll in some cases, resulting in an impossible build. Minor DPS Score buff to affected characters`,
        `Balance: The Wind-Soaring Valorous 4p is now disabled by default, but activated by default only for specific characters who can benefit from it`,
        `Balance: Updated Jiaoqiu to have 3x stacks of Prisoner in Deep Confinement 4p by default`,
        `Balance: Updated Moze to have 3x+ stacks of Pioneer Diver of Dead Waters 4p by default`,
        `Balance: Updated Jade to have 8x stacks of The Ashblazing Grand Duke 4p by default`,
        `Balance: Updated Herta to have 8x stacks of The Ashblazing Grand Duke 4p by default`,
        `Balance: Updated Yunli to have 8x stacks of The Ashblazing Grand Duke 4p by default`,
        `Balance: Updated Himeko to have 8x stacks of The Ashblazing Grand Duke 4p by default`,
        `Balance: Revisited all characters weights and adjusted values for maximum-potential based relic scoring`,
        `Balance: Kafka weights`,
        `— Prev: 1.0 ATK / 1.0 SPD / 0.5 CR / 0.5 CD / 0.5 EHR / 0.75 BE`,
        `— Now: 1.0 ATK, 1.0 SPD, 0.5 EHR`,
        `Balance: Silver Wolf weights`,
        `— Prev: 0.5 ATK / 0.25 DEF / 0.25 HP / 1.0 SPD / 0.75 CR / 0.75 CD / 1.0 EHR / 0.75 BE`,
        `— Now: 0.5 DEF / 0.5 HP / 1.0 SPD / 1.0 EHR / 0.5 RES`,
        `Balance: Asta weights`,
        `— Prev: 0.75 ATK / 0.75 DEF / 0.75 HP / 1.0 SPD / 0.75 RES / 0.5 BE`,
        `— Now: 0.5 ATK / 0.5 DEF / 1.0 HP / 1.0 SPD / 0.5 RES / 0.5 BE`,
        `Balance: Bronya weights`,
        `— Prev: 0.75 DEF / 0.75 HP / 1.0 SPD / 1.0 CD / 0.75 RES`,
        `— Now: 0.5 DEF / 0.5 HP / 1.0 SPD / 1.0 CD / 0.75 RES`,
        `Balance: Pela weights`,
        `— Prev: 0.75 DEF / 0.75 HP / 1.0 SPD / 1.0 EHR / 0.75 RES`,
        `— Now: 0.75 DEF / 0.75 HP / 1.0 SPD / 1.0 EHR / 0.5 RES`,
        `Balance: Tingyun weights`,
        `— Prev: 1.0 ATK / 0.75 DEF / 0.75 HP / 1.0 SPD / 0.75 RES`,
        `— Now: 1.0 ATK / 0.75 DEF / 0.75 HP / 1.0 SPD / 0.5 RES`,
        `Balance: Fu Xuan weights`,
        `— Prev: 0.75 DEF / 1.0 HP / 1.0 SPD / 0.75 RES`,
        `— Now: 1.0 DEF / 1.0 HP / 1.0 SPD / 0.5 RES`,
        `Balance: Guinaifen weights`,
        `— Prev: 1.0 ATK / 1.0 SPD / 1.0 EHR / 0.75 BE`,
        `— Now: 1.0 ATK / 0.5 DEF / 0.5 HP / 1.0 SPD / 1.0 EHR / 0.5 RES`,
        `Balance: Hanya weights`,
        `— Prev: 0.75 DEF / 0.75 HP / 1.0 SPD / 0.75 RES`,
        `— Now: 0.75 DEF / 0.75 HP / 1.0 SPD / 0.5 RES`,
        `Balance: Jiaoqiu weights`,
        `— Prev: 0.5 ATK / 0.5 DEF / 0.5 HP / 1.0 SPD / 1.0 EHR`,
        `— Now: 0.5 ATK / 0.5 DEF / 0.5 HP / 1.0 SPD / 1.0 EHR / 0.5 RES`,
        `Balance: Ruan Mei weights`,
        `— Prev: 0.75 DEF / 0.75 HP / 1.0 SPD / 0.75 RES / 1.0 BE`,
        `— Now: 0.5 DEF / 0.5 HP / 1.0 SPD / 0.5 RES / 1.0 BE`,
        `Balance: Aventurine weights`,
        `— Prev: 1.0 DEF / 0.5 HP / 1.0 SPD / 1.0 CR / 1.0 CD`,
        `— Now: 1.0 DEF / 1.0 SPD / 1.0 CR / 1.0 CD`,
        `Balance: Sparkle weights`,
        `— Prev: 0.75 DEF / 0.75 HP / 1.0 SPD / 1.0 CD / 0.75 RES`,
        `— Now: 0.5 DEF / 0.5 HP / 1.0 SPD / 1.0 CD / 0.5 RES`,
        `Balance: Black Swan weights`,
        `— Prev: 1.0 ATK / 1.0 SPD / 1.0 EHR / 0.5 BE`,
        `— Now: 1.0 ATK / 1.0 SPD / 1.0 EHR`,
        `Balance: Robin weights`,
        `— Prev: 1.0 ATK / 0.75 DEF / 0.75 HP / 1.0 SPD / 0.75 RES`,
        `— Now: 1.0 ATK / 0.5 DEF / 0.5 HP / 1.0 SPD / 0.5 RES`,
        `Balance: Firefly weights`,
        `— Prev: 1.0 ATK / 1.0 SPD / 1.0 BE`,
        `— Now: 0.5 ATK / 1.0 SPD / 1.0 BE`,
        `Balance: Boothill weights`,
        `— Prev: 0.5 ATK / 1.0 SPD / 0.75 CR / 0.75 CD / 1.0 BE`,
        `— Now: 0.25 ATK / 1.0 SPD / 0.25 CR / 0.25 CD / 1.0 BE`,
        `Balance: Trailblazer Harmony weights`,
        `— Prev: 0.75 DEF / 0.75 HP / 1.0 SPD / 0.75 RES / 1.0 BE`,
        `— New: 0.5 DEF / 0.5 HP / 1.0 SPD / 0.5 RES / 1.0 BE`,
        `Keep in mind with the new substat scoring system, a reduction in one stat's weight now actually makes the other substats worth more`,
        `Meaning in most cases these weight reductions actually are buffs to the scores of good relics`,
      ],
    },
    {
      title: '',
      date: '2024-08-19',
      content: [
        `Added a new Combat Stats view for the score card, showing the character's fully buffed in-combat details`,
        `combat.webp`,
        `Added a new toggle to switch between Combat Stats and Damage Upgrades card view`,
        `upgrades.webp`,
        `Added a new panel to suggest filter changes when optimizer searches produce zero results`,
        `popup.webp`,
        `Updated scoring card with better rules for showing relevant stats`,
        `Renamed Sim Damage to Combo DMG for clarity`,
        `stats.webp`,
        `Updated Edit Character menu to auto-populate the light cone path, added path icons`,
        `Switching light cones will now reset its superimposition to S1`,
        `modal.webp`,
        `Relic scorer card now has an Edit character button`,
        `edit.webp`,
        `Moved Relic Scorer tab to a new Showcase menu at the top of the sidebar for visibility`,
        `showcase.webp`,
        `Updated content to version 2.5v4`,
        `Editing a relic now re-scores it automatically and updates the Relics tab grid`,
        `Updated Kel-Z and Reliquary Archiver imports to support the new v4 format`,
        `Fix: Some relic set text descriptions were out of date`,
        `Fix: Importing relics no longer overwrites the optimizer's equipped owner`,
        `Balance: Kafka / Black Swan's sim scoring updated to lean more towards DoT`,
        `Balance: Moze's default sim updated to to 4p Pioneer, allow Ashblazing and Izumo`,
        `Balance: Feixiao's damage combo updated to remove Break, updated combo with her ult changes`,
      ],
    },
    {
      title: '',
      date: '2024-08-10',
      content: [
        `Added Healing Boost and Energy Regen on the character score card`,
        `Removed CV from the stat card`,
        `card.webp`,
        `Optimizer builds can now be pinned to the top of the grid for easier comparisons`,
        `pin.webp`,
        `The Relic scorer can now import characters along with relics`,
        `import.webp`,
        `Updated the Edit character menu with more convenient selectors`,
        `edit.webp`,
        `Added estimated time remaining to optimizer searches`,
        `eta.webp`,
        `Added an Equipped state filter to the Relics tab`,
        `equipped.webp`,
        `Added Lushaka set to teammate effects`,
        `lushaka.webp`,
        `Updated with 2.5 beta data`,
        `Fix: Conditional sliders max/min selections will now update properly when eidolons change`,
        `Fix: The baseline simulation will now use the best default set when the user's character isn't using an equivalent set`,
        `Fix: Lingsha calculations now correctly take into account teammate super break triggers`,
        `Balance: Himeko's default ornament set is now Duran`,
        `Balance: Dr Ratio's default ornament set is now Duran`,
        `Balance: Feixiao secondary ult now forces weakness break to enabled`,
        `Balance: Removed break damage from Feixiao's rotation`,
        `Balance: Adjusted logic for simulation scoring using speed boots vs atk boots`,
      ],
    },
    {
      title: '',
      date: '2024-07-08',
      content: [
        `Buffed DPS scores across all characters, making the 100% benchmark slightly easier to reach`,
        `benchmark.webp`,
        `The Characters tab now has a search bar, and filters for element / path`,
        `search.webp`,
        `The Relics tab custom characters menu now has buttons to Exclude all / Clear`,
        `Custom view is now the default`,
        `exclude.webp`,
        `Reliquary archiver is back online and been updated for v2.3, new download required`,
        `reliquary.webp`,
        `Re-formatted optimizer grid headers for readability`,
        `grid.webp`,
        `Characters' default scoring combo is now automatically filled in on the optimizer`,
        `combo.webp`,
        `Updated Yunli's default scoring team`,
        `yunli.webp`,
        `Updated Yunli and March 8th's Ashblazing set calcs`,
        `Updated v2.3 characters conditional tooltips`,
        `Re-centered all light cones for simulation scoring view`,
        `Fix: Updated ability-type buff logic to correctly apply DMG buffs on characters that can change ability types`,
        `Fix: Aventurine now correctly applies CD buff on Unnerved`,
        `Fix: Certain relics weren't showing correctly in Hoyolab import`,
        `Fix: Duran and Lantern set stats are now applied correctly for scoring`,
        `Fix: Manual relic creation was broken in certain cases`,
        `Balance: Allow the scoring simulation to use Lantern/Talia sets as well as Cavalry on Harmony MC teams`,
        `Balance: Seele E1 CR buff is now disabled by default`,
        `Balance: March 8th now uses S5 Cruising in the Stellar Sea for scoring`,
      ],
    },
    {
      title: '',
      date: '2024-06-18',
      content: [
        'Added 2.4 characters and light cones',
        'beta.webp',
        'Changed DPS Score Improvements -> Damage improvements and updated the percentage to use damage',
        'damageImprovements.webp',
        'Added relic counter on the relics tab grid',
        'relicCount.webp',
        'The sorted optimizer column is now highlighted',
        'highlightColumn.webp',
        'Moved enemy options to an Enemy configurations menu under Advanced options',
        'advancedOptions.webp',
        'Added Effect RES as a customizable enemy option for DoT calcs',
        'enemyConfigurations.webp',
        'Added options to toggle seeing all / custom characters on the potential graph',
        'customCharacters.webp',
        'Expanded the Extra combat stats menu with more buff options',
        'combatBuffs.webp',
        'Added a new Boost main stat option to select the desired main stat upgrade level',
        'optimizerOptions.webp',
        'Added character icons to various places',
        'Character cards now zoom out properly for the smaller sim scoring portrait',
        `Fix: Herta's technique now disabled by default`,
        'Fix: Manually editing verified relics will now remove their verified status',
        'Fix: Elemental damage now shows correctly on the character card',
        'Fix: Corrected display bug on relics tab potential upgrades suggesting invalid stats',
        `Fix: Ruan Mei's E2 is now correctly calculated for Firefly`,
        'Fix: Harmony Trailblazer is now imported correctly from the scanners',
        'Balance: Increased DoT scoring for Luka / Sampo',
        'Balance: Adding Break Effect and Cavalry set as valid BiS scoring options when HMC is on the simulation team',
        'Balance: Adjusted multiple support characters main stats to be more flexible',
        `Balance: Firefly's scoring stats have been adjusted`,
        `Balance: Firefly's default sim now uses Cavalry / Lantern sets`,
      ],
    },
    {
      title: '',
      date: '2024-06-06',
      content: [
        'Improved relic edit menu UI, with automatic substat upgrade calculations',
        'relicModal.webp',
        'DPS Score upgrades section now shows the score improvement of switching main stats, and switching to BiS relic set',
        'scoreUpgrades.webp',
        'Adding option to switch between scoring types',
        'switchScoring.webp',
        'Added a settings menu for combat sim options',
        'scoringSettings.webp',
        'Added new Edit character button to the Characters tab for changing eidolons / lcs',
        'editCharacter.webp',
        'Added new Sim Damage stat for showing the simulated combo damage used for scoring',
        'simDamage.webp',
        'Added new version of the substat weight filter, to filter relics by minimum weighted rolls per gear slot',
        'substatWeight.webp',
        'Changed the scoring grade scale to balance DPS score changes',
        'newGrades.webp',
        'Updated build analysis section with more details about the benchmark builds',
        'buildAnalysis.webp',
        'Added HoyoLab import to the scanner options',
        'importer.webp',
        'Various other DPS score balance changes, detailed out in the methodology section. New benchmark ruleset measures against 0% / 100% / 200% builds',
        'Fix: Sets were not activating correctly in some cases for Aventurine',
        'Fix: Jade now correctly applies Ashblazing set buffs',
        'Fix: Boothill\'s Standoff conditional now correctly applies as a vulnerability instead of DMG increase',
        'Fix: Sleep Like the Dead\'s Crit Rate buff is now deactivated by default',
        'Fix: Cruising in the Stellar Sea\'s Crit Rate buff is now deactivated by default',
        'Fix: Adjusted Firefly and Boothill scoring main stats',
        'Fix: Ruan Mei scoring can now use all main stats for body / sphere',
      ],
    },
    {
      title: '',
      date: '2024-05-22',
      content: [
        'Updated with new character card layout',
        'Added damage simulation based character scoring',
        'newScore.webp',
        'Add custom teammates display',
        'customTeam.webp',
        'Added a substat upgrade calculation for damage scoring',
        'scoreUpgrades.webp',
        'More details about the simulation scoring can be found below the character card',
        'scoreSummary.webp',
        'Added EHR considerations for DoT damage calculation, assumes 20% enemy RES',
        'Adding customizable Rotation Combo damage formula',
        'comboMenu.webp',
        'The combo results can be filtered and sorted in the optimizer',
        'comboGrid.webp',
        'Added responsive handling to optimizer permutations sidebar, which now collapses into a footer for smaller screens',
        'footer.webp',
        'Moved Combat Buffs menu into a drawer',
        'combatBuffs.webp',
        'Added a +3 enhance button to the Relic Edit modal for easy enhancing',
        'plusThree.webp',
        'Added bar search to damage sim selectors',
        'Raised Robin’s ATK cap to 8000',
        'Raised Robin’s ATK default to 5000',
        'Reliquary version bumped to 0.1.6',
        'Character / light cone images are now blurred while loading',
        'Updated with beta 5.3v3 changes',
        'Fix: Fixed Firefly Break Effect conversion interaction with ratio converted ATK buffs (Robin/Lynx)',
        'Fix: Ruan Mei’s default sort is now Break Effect',
        'Fix: Robin’s default sort is now ATK',
        'Fix: Prevent Ult DMG buffs from applying to Robin’s ult (Salsotto)',
        'Fix: Removed Jade skill damage',
        'Fix: Sparkle now correctly applies her skill CD',
        'Fix: Custom character weights are now applied to the optimizer page',
        'Fix: Allow all main stats for Harmony MC on body and sphere',
        'Fix: Super break override now applies correctly to HMC',
        'Fix: Prevent teammate sync from adding messenger set to calculations',
        'Fix: Various relics tab potential optimality bugs have been fixed',
        'Fix: Characters with not enough desired stats now score correctly on relics tab',
        'Fix: Renamed Base stats to Basic stats',
      ],
    },
    {
      title: '',
      date: '2024-05-07',
      content: [
        'Added a new "Character custom stats simulation" feature',
        'This allows for simulating and comparing multiple character builds with custom main stats / teammates / sets / substats without having to edit relics',
        'The substat rolls view calculates builds based on the number of max rolls in each substat',
        'Optimizer builds can be imported as substat roll simulations',
        'rollSim.webp',
        'The substat totals view simulates the sum of the substat values',
        'totalsSim.webp',
        `Jade and Firefly have been added with damage calculations, and to the Relic Scorer experiment options`,
        'jade.webp',
        'Custom character portraits can now be saved from the Relic Scorer',
        'scorer.webp',
        'Updated Harmony Trailblazer with Super Break DMG calculations',
        `When the Super Break conditional is enabled, each ability's toughness DMG will be used to calculate Super Break DMG, which is added to the respective ability's damage column`,
        'superBreak.webp',
        'Added new 2.3 relic sets',
        'relics.webp',
        'Added new 2.3 ornament sets',
        'ornaments.webp',
        'Reliquary Archiver is now the recommended scanner',
        'Note: It may have a few hours of downtime following new ingame patches',
        'import.webp',
        'New updates will now show a notification linking to the changelog',
        'update.webp',
        'Added a new settings panel',
        'The first setting is toggle the behavior when equipping relics with another owner, which now defaults to replacing without swapping',
        'settings.webp',
        'Using the Recommended Presets button now takes into account custom scoring overrides',
        'Newly added characters will have their recommended presets applied by default',
        `Harmony Trailblazer's default teammate Break Effect conditional is now 200%, and the cap is increased to 400%`,
        `The Genius set's conditional effects are now only active by default on Quantum characters, and disabled by default otherwise`,
        `Fix: Tingyun SPD buff is now disabled by default due to having inconsistent uptime`,
        `Fix: Himeko's SPD buff is now disabled by default due to having inconsistent uptime`,
        `Fix: Qingque's SPD buff is now disabled by default due to having inconsistent uptime`,
        `Fix: Sparkle's self-skill buff is now disabled on herself by default`,
        `Fix: Bronya's battle-start buffs are now disabled by default`,
        `Fix: Asta's skill now correctly calculates the sum of the bounces for damage instead of an individual hit`,
        `Fix: Remove ATK% rope from Robin's presets`,
        'Fix: Main stat free rolls are now applied correctly to non-full-weight main stats. This results in a minor score buff for certain main stats',
        'Fix: Various visual overflow issues on small screens',
      ],
    },
    {
      title: '',
      date: '2024-04-18',
      content: [
        'Launched a new leak-free version of the optimizer which has no leaks and only contains officially released content',
        'https://starrailoptimizer.github.io',
        'noLeaks.webp',
        'Added a one-click-optimize button to the Relic Scorer page, accessed by clicking the graph icon or the Optimize Character Stats button',
        'This automatically imports the scored profile relics, adds the character and light cone, applies recommended filters and conditionals, and starts an optimizer search',
        'This is meant to be an easy way for new users to get started using the optimizer',
        'oneClick.webp',
        'Updated the Get Started tab with up to date instructions and a step-by-step guide to using the optimizer for the first time',
        'getStarted.webp',
        'Added new Average potential view as an option alongside Max potential on Relics tab',
        'potentialUpdates.webp',
        'Relic potential ratings menu now has a Custom characters view enabled by default, where only a subset of characters are considered for the potential calculations',
        'relicRatings.webp',
        'All characters are included initially, then specific characters can be selected to excluded from the relic potential view',
        'customCharacters.webp',
        'Clicking empty relic slots now brings up the Add New Relic menu',
        'clickEmpty.webp',
        'Added icons to sidebar menu tabs',
        'Added a button to hide the menu sidebar for easier viewing on smaller screens',
        'hideSidebar.webp',
        'Updated the Recommended Presets speed breakpoints to 1000ths precision',
        'breakpoints.webp',
        'Ambiguous speed values near specific breakpoints (such as 133.333..) are now displayed to 1000ths precision for checking if the breakpoint is met',
        'spdValues.webp',
        'Added a Reset All Characters button to the scoring algorithm menu',
        'resetAll.webp',
        'Rephrased pioneer conditional to specify between basic and combat stat buffs',
        'The last optimized character will now be open by default on the next session',
        'The Simulate Relics On Another Character menu is now open by default on the Relic Scorer tab',
        'Updated Boothill damage calcs',
        'Updated Robin damage calcs',
        'Fix: Herta now correctly defaults to FUA sort',
        'Fix: Removed leftover unused character level selectors, all characters now default to level 80',
        'Fix: Black Swan E1 now correctly only applies res shred on DOT elements',
        'Fix: Scores for saved builds will now update with scoring changes',
        'Fix: Creating new relics with an owner now equips the relic',
      ],
    },
    {
      title: '',
      date: '2024-04-04',
      content: [
        'Added Break DMG calculations for all characters and a sortable BREAK column in the optimizer grid',
        'breakDmg.webp',
        'Updated Boothill\'s Enhanced basic attack calculation to include his Talent\'s additional break damage',
        'Updated Boothill\'s conditional toggle to be "Talent break DMG (forces weakness break)" which overrides the weakness break option when enabled',
        'Updated Boothill\'s default sort option to Basic DMG',
        'boothill.webp',
        'Updated Boothill\'s scoring algorithm to prioritize SPD and Break Effect',
        'boothillScore.webp',
        'Added a display for the artist\'s name on custom character portraits',
        'artist.webp',
        'The artist name can be updated along with the image on the crop menu',
        'Enabled gif uploads for custom character portraits',
        'artistInput.webp',
        'Updated Reliquary Archiver import for 2.1 patch, which imports accurate speed decimals for the entire inventory',
        'archiver.webp',
        'Added new character action menu entry to "Sort by score" which rearranges the character priority by their character scores',
        'sortByScore.webp',
        'Updated conditional set effects for Pioneer Diver of Dead Waters set with a 0x debuffs option which disables the 2p effect',
        'pioneer.webp',
        'Removed the Enemy HP% selector from the enemy options panel, and replaced it with Enemy Toughness, which affects the Break DMG calculations in the optimizer',
        'tough.webp',
        'Since the Enemy HP% selector was removed, updated character conditionals that depended on it to have their own toggle',
        'Dan Heng now has an enemy HP% threshold toggle',
        'Himeko now has an enemy HP% threshold toggle',
        'Herta now has an enemy HP% threshold toggle',
        'Argenti now has an enemy HP% threshold toggle',
        'Reduced the filesize of assets for faster image loading',
        'Optimizer search speed improvements for unfiltered searches',
        'Added warning popup for optimizer searches with mismatching character and light cone paths',
        'Ruan Mei\'s teammate buff renamed to "Overtone buff" and now also applies her weakness break efficiency buff',
        'Gallagher\'s Besotted buff added with Break DMG vulnerability',
        'Fix: Argenti A6 trace now correctly applies to all his abilities instead of just ult DMG',
        'Fix: Updated tooltips for 2.1 light cones',
        'Fix: Updated Along the Passing Shore light cone\'s passive effect to Mirage Fizzle',
        'Fix: Planetary Rendezvous now shows correctly on the teammate buffs panel',
        'Fix: Bug with unselectable main stats being available in the Edit Relic view in certain cases',
        'Fix: Stat filters are now saved to 1000ths precision',
      ],
    },
    {
      title: '',
      date: '2024-03-26',
      content: [
        'Added custom character portrait images, through the "Edit portrait" menu button on the character preview/relic scorer',
        'sparkle.webp',
        'Portrait images can be selected by url or uploaded from file',
        'crop.webp',
        'Added substat roll count indicators to relics, showing the number of additional rolls per stat',
        'rollQuality.webp',
        'Added new relic rating tools to the Relics tab: for evaluating relic potential for the selected character or all characters',
        'When selecting a character on the Relics grid, all selected relics will show their score according to the selected character\'s weights',
        'relicsGrid.webp',
        'Added new Relic Insights: Buckets graphs to display the potential of a relic and which characters are the best fit for the stats',
        'relicBuckets.webp',
        'The Relic Insights: Top 10 view shows the min/max range of potential for the top 10 best fit characters',
        'relicTop10.webp',
        'Added new 2.1 sets: Sigonia, the Unclaimed Desolation & Izumo Gensei and Takama Divine Realm',
        '21sets.webp',
        'Added new importer option for the Reliquary Archiver (beta) which can import accurate speed decimals for the entire inventory',
        'importer.webp',
        'Added new Optimization Target options to the optimizer page.',
        'optimimationTarget.webp',
        'This removes the 2 million results hard cap from before.',
        'resultsLimit.webp',
        'Choose the desired optimization goal for damage/stats/rating, and select a results limit, to find the top search results sorted by the target',
        'sortBy.webp',
        'Stat decimals are now shown to 1000ths precision on the Character preview when hovered',
        'spdHover.webp',
        'Added new Character action to switch relics with another character',
        'switchRelics.webp',
        'Added new 2.2 characters: Robin / Boothill / Harmony Trailblazer',
        'Added new 2.2 light cones: Boundless Choreo / For Tomorrow\'s Journey / Flowing Nightglow / Sailing Towards A Second Life',
        '22chars.webp',
        'Adjusted character optimal main stats, allowing more lenient options such as ATK% spheres for DPS and any sphere stats for Bronya/Sparkle',
        'Removed level selectors on Optimizer tab - all optimizations now assume level 80 character and light cone',
        'Made the sidebar menu always stay on screen when scrolling',
        'Fix: Relic imports from scanning newly rolled relics before logout no longer causes duplicate relics',
        'Fix: Download screenshot button on mobile devices and Safari browsers now generates the image correctly',
        'Fix: Pela E2 skill conditional SPD buff is now off by default',
        'Fix: Bronya technique conditional ATK buff is now off by default',
        'Fix: Silver Wolf skill conditional weakness implanted RES shred is now off by default',
        'Fix: Sparkle talent conditional Quantum allies ATK buff now only applies to Quantum elemental main characters',
        'Fix: Acheron trace Stygian Resurge now has its own slider instead of assuming all hits on target',
        'Fix: Seele E1 conditional CR buff now has its own toggle instead of being linked to the enemy HP selector',
      ],
    },
    {
      title: '',
      date: '2024-03-12',
      content: [
        'Added a new visual character selector menu with search and filters',
        'charSelect.webp',
        'Light cone selectors are also updated and now default to the selected character\'s path',
        'lcSelect.webp',
        'Added a new menu that automatically shows suggestions to fix common misconfigurations in setting up optimizer searches that result in 0 permutations',
        'zeroPerm.webp',
        'Presets speed breakpoints are now defined to 100ths precision',
        'presets.webp',
        'Added def values to enemy level selector',
        'enemyDef.webp',
        'Updated calculations with the latest beta character abilities',
        'Reorganized some stat orderings for consistency',
        'Fix: Light cone "Today is Another Peaceful Day" now defaults to the character\'s max energy',
        'Fix: E2/E5 eidolon calculations for some characters',
        'Fix: EHP filter works again',
        'Fix: Linking to #scorer and other pages works again',
        'Fix: Permutations now refresh when navigating to Optimizer tab',
        'Fix: Alerts can now be closed when clicking on them',
      ],
    },
    {
      title: '',
      date: '2024-02-28',
      content: [
        'Enabled up/down arrow key navigation for grids',
        'Updated the selected row overlay to be more visible',
        'gridRow.webp',
        'Added new priority and exclusion selectors in optimizer options',
        'Priority can now be changed from the optimizer tab now instead of dragging. Exclude will additionally filter out specific characters relics',
        'priorityExclude.webp',
        'Added a notice to update when the scanner version is out of date',
        'outOfDate.webp',
        'Relic scorer Simulate button has been move to a sidebar, and now has preset characters for current/upcoming banners',
        'simulate.webp',
        'Added a sortable CV column for crit value to the Relics tab',
        'cvColumn.webp',
        'Added a "Move to top" action button to the Characters tab',
        'moveToTop.webp',
        'Started adding more icons to selectors for readability, more to come',
        'icons.webp',
        'Removed CV column & filter from optimizer tab - damage calculations are a better option to sort by now',
        'Stats display is set to "Combat Stats" by default now, also the setting now saves correctly per character',
        'Changed relic scorer API in preparation for upcoming leaderboards update',
      ],
    },
    {
      title: '',
      date: '2024-02-20',
      content: [
        'Added: Acheron / Aventurine / Gallagher',
        'newChars.webp',
        'Added: "Simulate relics on another character" button on the Relic scorer.',
        'Now the profile characters\' builds can be simulated as unowned or unreleased characters & light cones to preview their gear with accurate base stats',
        'simulate.webp',
        'Added: Teammates menu for the optimizer. This automatically adds the teammate\'s character passives/eidolons/light cone/relic sets to the calculations for more accurate results',
        'teammates.webp',
        'Added: Character builds can now be saved as loadouts, keeping a history of saved builds that can be easily swapped between',
        'savedBuilds.webp',
        'Added: Changelog page to track new optimizer changes',
        'changelog.webp',
        'Moved stat display to the sidebar for easier access',
        'statDisplay.webp',
        'Clicking "Start optimizing" now scrolls the page down to the results grid',
        'Deprecated the Fribbels scanner option in favor of the Kel-Z scanner',
        'Energy Regeneration Rate column can be filtered on now',
        'Imports now work with scanner files that only contain characters/light cones without relics',
        'Minor scoring changes for: Sushang, Luka, Physical Trailblazer, Blade, Silver Wolf, Kafka, and Preservation characters',
      ],
    },
    {
      title: '',
      date: '2024-02-05',
      content: [
        'Added \'Recommended Presets\' button to fill out the optimizer with some suggested values',
        'presets.webp',
        'Added the new Pioneer & Watchmaker relic sets',
        'newSets.webp',
        'Added support for 8 relic scorer slots',
        'scorer8Characters.webp',
        'All character and light cone passives now have descriptions on hover',
        'skillDescriptions.webp',
        'Reorganized Character tab buttons with new Add / Edit character actions',
        'characterActions.webp',
        'Added a Screenshot button for copying the character preview to clipboard / downloads',
        'screenshot.webp',
        'Added a progress bar for the search',
        'progress.webp',
        'Updated damage calcs with all 2.0 light cones',
        'Relic set filters now have a 2 piece + Any option',
        'Improved optimizer search performance, should run 3-6x faster now',
      ],
    },
    {
      title: '',
      date: '2024-01-22',
      content: [
        'Black Swan / Sparkle / Misha added with dmg calcs and their signature light cones',
        'newChars.webp',
        'New \'Use equipped relics\' optimizer filter toggle',
        'useEquipped.webp',
        'Optimizer grid now shows speed decimals',
        'spd.webp',
        'QOLs for relic editing for autofilled main stats',
        'Double clicking on the characters list now will navigate to the optimizer',
      ],
    },
    {
      title: '',
      date: '2024-01-13',
      content: [
        'Big update to the relics tab, including filters and a relic recommendation tool',
        'The recommendation tool scores each relic by its potential at +15 to help with picking which unenhanced relics to roll while building characters',
        'relicsTab.webp',
        'Also updated the Relic Scorer with an import option - now you can import relics directly from your ingame profile characters, with accurate speed values',
        'import.webp',
      ],
    },
    {
      title: '',
      date: '2024-01-06',
      content: [
        'Accurate damage calculations for every character, and new optimization columns for average Basic / Skill / Ult / Follow-up / DoT damage',
        'calcs.webp',
        'Character abilities + Light cone passive selectors to customize the damage simulation',
        'passives.webp',
        'Relic set effects menu for customizing which sets to activate',
        'setEffects.webp',
        'New filtering tools including the substat weight filter to reduce permutations & improve search time',
        'weightFilter.webp',
        'Enemy count / DEF / RES / HP / and weakness selectors for optimizing specific combat scenarios',
        'enemyOptions.webp',
        'Integrated with the Kel-Z HSR Scanner for faster & more accurate scans',
        'importer.webp',
        'Expanded combat buffs options for adding more team effects like SPD / DMG% / DEF & RES shred / etc',
        'Relic stat editor and better handling for hidden decimals',
        'New character importer option - Import all your character builds and light cones directly from the game',
      ],
    },
  ]
  // Filter out leaks from changelog
  changelog.map((x) => x.content = x.content.filter((x) => x.length > 0))
  return changelog
}
