import { Form } from 'types/Form';
import { ComputedStatsObject } from "lib/conditionals/constants";
import { FormSwitchWithPopoverProps } from "components/optimizerForm/conditionals/FormSwitch";
import { FormSliderWithPopoverProps } from "components/optimizerForm/conditionals/FormSlider";

export type ConditionalMap = {
  [key:string]: number | boolean | string | undefined;
};

// interface to an instance of a Character or Light Cone conditional controller
export interface Conditional {
  // getContent: () => { [key: string]: unknown }[];
  display: () => JSX.Element;
  defaults: () => ConditionalMap;
  // TODO: purify this implmeentation
  // ComputedStatsObject arg is mutated by ref
  calculateBaseMultis: (c: ComputedStatsObject, request: Form) => void;
  calculatePassives?: () => void;
}

// extracted content to apply to <DisplayFormControl />
export type ContentItem = {
  formItem: FormSwitchWithPopoverProps | FormSliderWithPopoverProps;
  text: string;
  title: string;
  content: JSX.Element | string;
  [key:string]: unknown;
}

export type ConditionalBuff =
  | 'activeShieldDmgDecrease' 
  | 'alliesSameElement'
  | 'arcanaStacks'
  | 'atkBoostStacks'
  | 'atkBuffActive'
  | 'atkBuffStacks'
  | 'basicEnhanced'
  | 'basicEnhancedExtraHits'
  | 'basicEnhancedSpdBuff'
  | 'basicEnhancements'
  | 'battleStartDefBuff'
  | 'benedictionBuff'
  | 'buffedState'
  | 'burdenAtkBuff'
  | 'cdBuffActive'
  | 'cipherBuff'
  | 'critSpdBuff'
  | 'debuffCdStacks'
  | 'debuffStacksDmgIncrease'
  | 'defDecreaseDebuff'
  | 'defeatedEnemyAtkStacks'
  | 'defeatedEnemyCdBuff'
  | 'defeatedEnemyCrBuff'
  | 'dmgBoost'
  | 'dmgBuff'
  | 'dmgReductionBuff'
  | 'dmgResBuff'
  | 'dragonsCallStacks'
  | 'e1CdBuff'
  | 'e1DebtorStacks'
  | 'e1DotDmgReceivedDebuff'
  | 'e1EnhancedState'
  | 'e1ResReduction'
  | 'e1TalentSpdBuff'
  | 'e1TargetBleeding'
  | 'e1TargetFrozen'
  | 'e2BurnMultiBoost'
  | 'e2DefReduction'
  | 'e2DmgBuff'
  | 'e2DmgReductionBuff'
  | 'e2SkillDmgBuff'
  | 'e2SkillSpdBuff'
  | 'e2TalentCritStacks'
  | 'e2UltAtkBuff'
  | 'e2UltHealingBuff'
  | 'e4BeBuff'
  | 'e4CurrentHp80'
  | 'e4DmgReductionBuff'
  | 'e4MaxHpIncreaseStacks'
  | 'e4SkillHealingDmgBuffStacks'
  | 'e4SkillResShred'
  | 'e4TalentAtkBuff'
  | 'e4TalentStacks'
  | 'e6DefStacks'
  | 'e6DmgBuff'
  | 'e6FuaVulnerabilityStacks'
  | 'e6ResPenStacks'
  | 'e6ResReduction'
  | 'e6TeamHpLostPercent'
  | 'e6UltAtkBuff'
  | 'e6UltDmgBoost'
  | 'e6UltExtraHits'
  | 'e6UltTargetDebuff'
  | 'eclipseStacks'
  | 'enemies2CrBuff'
  | 'enemy3DebuffsCrBoost'
  | 'enemyBurned'
  | 'enemyBurnedBleeding'
  | 'enemyCountAtkBuff'
  | 'enemyDebuffed'
  | 'enemyDebuffedDmgBoost'
  | 'enemyDebuffStacks'
  | 'enemyDefeatedAtkBuff'
  | 'enemyDefeatedBuff'
  | 'enemyDmgTakenDebuff'
  | 'enemyFrozen'
  | 'enemyHp50CrBoost'
  | 'enemyHp50FuaBuff'
  | 'enemyHpHigherDmgBoost'
  | 'enemyProofOfDebtDebuff'
  | 'enemyShockWindShear'
  | 'enemySlowed'
  | 'enemyToughness50'
  | 'enemyWeaknessBreakDmgBuff'
  | 'enhancedBasic'
  | 'enhancedSkill'
  | 'enhancedStateActive'
  | 'enhancedUlt'
  | 'epiphanyDebuff'
  | 'extraDmgProc'
  | 'fieldActive'
  | 'fuaDmgBoost'
  | 'fuaHits'
  | 'healingMaxHpBuff'
  | 'hpLostDmgBuff'
  | 'hpPercentLostTotal'
  | 'initialDmgReductionBuff'
  | 'initialSpeedBuff'
  | 'maxEnergyDmgBoost'
  | 'maxEnergyStacks'
  | 'maxEnergyUltDmgStacks'
  | 'maxStackDefPen'
  | 'missedCritCrBuff'
  | 'numbyEnhancedState'
  | 'postSkillDmgBuff'
  | 'postSkillHealBuff'
  | 'postSkillHealBuff'
  | 'postUltBuff'
  | 'postUltDmgBuff'
  | 'postUltDotDmgBuff'
  | 'postUltHealingBoost'
  | 'postUltSpdBuff'
  | 'quantumAllies'
  | 'resToHealingBoost'
  | 'roaringBowstringsActive'
  | 'sameTargetHitStacks'
  | 'selfAttackedDefBuff'
  | 'selfCurrentHp80Percent'
  | 'selfCurrentHpPercent'
  | 'shieldActive'
  | 'skillActive'
  | 'skillBuff'
  | 'skillCdBuff'
  | 'skillCritBuff'
  | 'skillDefShredDebuff'
  | 'skillDmgIncreaseStacks'
  | 'skillExtraDmgHits'
  | 'skillExtraHits'
  | 'skillOutroarStacks'
  | 'skillRemovedBuff'
  | 'skillResShredDebuff'
  | 'skillSpdBuff'
  | 'skillTriggerStacks'
  | 'skillUltDmgBoost'
  | 'soulsteelBuffActive'
  | 'spdDmgBuff'
  | 'spdScalingBuffs'
  | 'spdStacks'
  | 'speedBoostStacks'
  | 'summationStacks'
  | 'talentAttacks'
  | 'talentBuffStacks'
  | 'talentDebuffStacks'
  | 'talentDmgReductionBuff'
  | 'talentEnemyMarked'
  | 'talentEnhancedState'
  | 'talentHitsPerAction'
  | 'talentHpDrainAtkBuff'
  | 'talentPenBuff'
  | 'talentRighteousHeartStacks'
  | 'talentSpdBuffStacks'
  | 'talentStacks'
  | 'targetBurdenActive'
  | 'targetBurned'
  | 'targetCodeDebuff'
  | 'targetDebuffs'
  | 'targetDotTakenDebuff'
  | 'targetEnsnared'
  | 'targetFrozen'
  | 'targetShocked'
  | 'targetTameStacks'
  | 'targetUltDebuffed'
  | 'targetWindShear'
  | 'techniqueBuff'
  | 'toughnessReductionDmgBoost'
  | 'ultBuff'
  | 'ultBuffActive'
  | 'ultBuffedState'
  | 'ultDefPenDebuff'
  | 'ultDefShredDebuff'
  | 'ultDmgBuff'
  | 'ultEnhanced'
  | 'ultEnhancedExtraHits'
  | 'ultFieldActive'
  | 'ultHitsOnTarget'
  | 'ultSpdBuff'
  | 'weaknessBreakDmgBuff'
  ;