name: Reviewdog Tests
on:
  push:
    branches: [ main, beta ]
  pull_request:
    branches: [ main, beta ]
    types: [ opened, reopened, synchronize, review_requested, ready_for_review ]
jobs:
  tsc:
    name: runner / tsc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EPMatt/reviewdog-action-tsc@v1
        with:
          reporter: 'github-check'
          level: 'warning'
          filter_mode: 'nofilter'
          tsc_flags: 'noEmit'
