name: starrailoptimizer

on:
  push:
    branches: [ beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v2
      - name: Find and Replace homepage
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "\"homepage\": \"https://fribbels.github.io/hsr-optimizer\""
          replace: "\"homepage\": \"https://starrailoptimizer.github.io\""
          include: "package.json"
      - name: Find and Replace vite page
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "base: '/hsr-optimizer'"
          replace: "base: '/'"
          include: "vite.config.ts"
      - name: Find and Replace router path
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "const BASE_PATH = '/hsr-optimizer'"
          replace: "const BASE_PATH = ''"
          include: "src/lib/db.js"
      - name: Find and Replace API endpoint
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "const API_ENDPOINT = 'https://o4b6dqwu5a.execute-api.us-east-1.amazonaws.com/prod'"
          replace: "const API_ENDPOINT = 'https://9di5b7zvtb.execute-api.us-west-2.amazonaws.com/prod'"
          include: "src/components/RelicScorerTab.jsx"
      - name: Find and Replace officialOnly
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "window.officialOnly = false"
          replace: "window.officialOnly = true"
          include: "src/index.jsx"
      - run: rm -rf .github/workflows
      - run: mv .github/starrailoptimizer .github/workflows
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.STAR_RAIL_OPTIMIZER_SSH_DEPLOY_KEY }}
        with:
          source-directory: '.'
          destination-github-username: 'starrailoptimizer'
          destination-repository-name: 'starrailoptimizer.github.io'
          target-branch: main
